### ISSUE TITLE
Feature Request: Handle attachments

### ISSUE THREAD

**Issue by cheyngoodman** [c0sco/ansible-modules-bitwarden#10]
Bitwarden has a file attachment feature with premium membership.

Can this module be updated to support the deployment of attached files?

A basic use case would be:

- A user creates SSH key files and uploads them to Bitwarden as attachments
- This module deploys the attached SSH key files from Bitwarden

**Comment by c0sco** [comment]
I would love this functionality as well. I admit, I probably won't have time to implement this any time soon, but would be happy to approve a PR.

**Comment by c0sco** [comment]
This is closed #12
